[package]
name = "chip-again"
version = "0.1.0"
authors = ["ATune <atune313@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
structopt-derive = "0.3.4"
structopt = "0.3.4"
console = "0.9.1"
rand = "0.7.3"
crossterm = "0.14.2"
thiserror = "1.0.9"
log = "0.4.8"
env_logger = "0.7.1"
